name: Daily Scraping

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      run: python main_datos_zalando.py
